### ISSUE TITLE
having trouble building firmware

### ISSUE THREAD

**Issue by wagyuA5** [esrille/new-keyboard#17]
Hello I am trying to build my own firmware however the build keeps failing. I am using MPLAB X IDE v5.5 and XC8 v1.34. Is there something I am doing wrong?

```
make -f nbproject/Makefile-PIC18F4550_NISSE.mk SUBPROJECTS= .build-conf
make[1]: Entering directory 'C:/Users/JJ/Downloads/new-keyboard-master1/new-keyboard-master/firmware/third_party/mla_v2013_12_20/apps/usb/device/hid_keyboard/firmware/MPLAB.X'
make  -f nbproject/Makefile-PIC18F4550_NISSE.mk dist/PIC18F4550_NISSE/production/MPLAB.X.production.hex
make[2]: Entering directory 'C:/Users/JJ/Downloads/new-keyboard-master1/new-keyboard-master/firmware/third_party/mla_v2013_12_20/apps/usb/device/hid_keyboard/firmware/MPLAB.X'
"C:\Program Files (x86)\Microchip\xc8\v1.34\bin\xc8.exe" --pass1  --chip=18F4550 -Q -G    --double=24 --float=24 --emi=wordwrite --rom=default,-0-17FF,-1806-1807,-1826-1827 --opt=+asm,-asmfile,-speed,+space,-debug --addrqual=ignore --mode=free -DKANA_MAX=KANA_X6004 -P -N255 -I"../../../../../../../../src" -I"../src" -I"../../../../../../framework" -I"../../../../../../bsp/esrille_new_keyboard" -I"../src/system_config/esrille_new_keyboard" --warn=0 --asmlist -DXPRJ_PIC18F4550_NISSE=PIC18F4550_NISSE  --summary=default,-psect,-class,+mem,-hex,-file --codeoffset=0x1800 --output=default,-inhx032 --runtime=default,+clear,+init,-keep,-no_startup,-download,+config,+clib,+plib   --output=-mcof,+elf:multilocs --stack=compiled:auto:auto:auto "--errformat=%f:%l: error: (%n) %s" "--warnformat=%f:%l: warning: (%n) %s" "--msgformat=%f:%l: advisory: (%n) %s"     -obuild/PIC18F4550_NISSE/production/_ext/838585624/usb_device.p1 ../../../../../../framework/usb/src/usb_device.c 
make[2]: *** [build/PIC18F4550_NISSE/production/_ext/838585624/usb_device.p1] Error 1
make[1]: *** [.build-conf] Error 2
make: *** [.build-impl] Error 2
(908) exit status = 1
nbproject/Makefile-PIC18F4550_NISSE.mk:251: recipe for target 'build/PIC18F4550_NISSE/production/_ext/838585624/usb_device.p1' failed
make[2]: Leaving directory 'C:/Users/JJ/Downloads/new-keyboard-master1/new-keyboard-master/firmware/third_party/mla_v2013_12_20/apps/usb/device/hid_keyboard/firmware/MPLAB.X'
nbproject/Makefile-PIC18F4550_NISSE.mk:91: recipe for target '.build-conf' failed
make[1]: Leaving directory 'C:/Users/JJ/Downloads/new-keyboard-master1/new-keyboard-master/firmware/third_party/mla_v2013_12_20/apps/usb/device/hid_keyboard/firmware/MPLAB.X'
nbproject/Makefile-impl.mk:39: recipe for target '.build-impl' failed

BUILD FAILED (exit value 2, total time: 962ms)
```

**Comment by ShikiOkasaka** [comment]
Your build environment might have been corrupted.
It seems MPLAB X IDE v5.5 checks the project properties more strictly.
We've just committed new MPLAB.X files for MPLAB X IDE v5.50 at 755365b34cbba20c485444e2d1a86b36538c384f.
Please clean up your current build tree and use the updated XML files with your MPLAB X IDE.
You would also need to manually install the following Packs files by selecting the Tools/Packs menu item from the IDE:

- PIC18Fxxxx_DEP (1.1.19)
- PIC18F-J_DEP (1.1.24)

We have checked that the new project files work fine with MPLAB X IDE v5.50 on Windows 10 and Ubuntu 21.10 so far.

**Comment by wagyuA5** [comment]
Hello I downloaded the new branch and in tools->packs menu I could only find and install the DFP versions. Here are the errors I am getting now.

Configuration Loading Error
```
warning: Configuration "PIC18F4550_NISSE" builds with "XC8 v1.34", but indicates no toolchain directory.
info: Configuration "PIC18F4550_NISSE" will build with toolchain "XC8 v1.34" at "C:\Program Files (x86)\Microchip\xc8\v1.34\bin".

Could not generate makefiles for configuration PIC18F4550_NISSE.

XMLBaseMakefileWriter::getAssembly, assembly is null
Errors have occurred while loading one or more configurations.
If a specific error is not shown above, this may happen when you import a project from another computer.
    + You can add language tools in Tools->Options embedded tab.
    + You can change which language tool to use in the project properties dialog.

```
and here is the build error
```
make -f nbproject/Makefile-PIC18F4550_NISSE.mk SUBPROJECTS= .build-conf
make[1]: *** No rule to make target '.build-conf'.  Stop.
make[1]: Entering directory 'C:/Users/JJ/Downloads/esrille_nisse/new-keyboard-master/firmware/third_party/mla_v2013_12_20/apps/usb/device/hid_keyboard/firmware/MPLAB.X'
make: *** [.build-impl] Error 2
make[1]: Leaving directory 'C:/Users/JJ/Downloads/esrille_nisse/new-keyboard-master/firmware/third_party/mla_v2013_12_20/apps/usb/device/hid_keyboard/firmware/MPLAB.X'
nbproject/Makefile-impl.mk:39: recipe for target '.build-impl' failed

BUILD FAILED (exit value 2, total time: 101ms)

```

**Comment by ShikiOkasaka** [comment]
Please check that your project properties are like the attached image.
![screenshot](https://user-images.githubusercontent.com/3130013/140437832-4554f1d2-b28c-41e0-b01a-7b349422a633.png)
The version numbers of the XC8 and Packs are important.
Then hit [Apply] and try [Production] / [Clean and Build Main Project].

The following thread might be helpful, too:
https://www.microchip.com/forums/m890438.aspx

**Comment by wagyuA5** [comment]
Here are the properties I am using:

![nisseproperties](https://user-images.githubusercontent.com/68674843/140547691-c5869ade-f9b4-4d24-a5bf-b9864f74bb77.PNG)


This is the output I get by using Clean and Build project: 

``` 

CLEAN SUCCESSFUL (total time: 10ms)
make -f nbproject/Makefile-PIC18F4550_NISSE.mk SUBPROJECTS= .build-conf
make[1]: Entering directory 'C:/Users/JJ/Downloads/new-keyboard-master/new-keyboard-master/firmware/third_party/mla_v2013_12_20/apps/usb/device/hid_keyboard/firmware/MPLAB.X'
make  -f nbproject/Makefile-PIC18F4550_NISSE.mk dist/PIC18F4550_NISSE/production/MPLAB.X.production.hex
make[2]: Entering directory 'C:/Users/JJ/Downloads/new-keyboard-master/new-keyboard-master/firmware/third_party/mla_v2013_12_20/apps/usb/device/hid_keyboard/firmware/MPLAB.X'
"C:\Program Files (x86)\Microchip\xc8\v1.34\bin\xc8.exe" --pass1  --chip=18F4550 -Q -G    --double=24 --float=24 --emi=wordwrite --rom=default,-0-17FF,-1806-1807,-1826-1827 --opt=+asm,-asmfile,-speed,+space,-debug --addrqual=ignore --mode=free -DKANA_MAX=KANA_X6004 -P -N255 -I"../../../../../../../../src" -I"../src" -I"../../../../../../framework" -I"../../../../../../bsp/esrille_new_keyboard" -I"../src/system_config/esrille_new_keyboard" --warn=0 --asmlist -DXPRJ_PIC18F4550_NISSE=PIC18F4550_NISSE  --summary=default,-psect,-class,+mem,-hex,-file --codeoffset=0x1800 --output=default,-inhx032 --runtime=default,+clear,+init,-keep,-no_startup,-download,+config,+clib,+plib   --output=-mcof,+elf:multilocs --stack=compiled:auto:auto:auto "--errformat=%f:%l: error: (%n) %s" "--warnformat=%f:%l: warning: (%n) %s" "--msgformat=%f:%l: advisory: (%n) %s"     -obuild/PIC18F4550_NISSE/production/_ext/1360937237/app_led_usb_status.p1 ../src/app_led_usb_status.c 
"C:\Program Files (x86)\Microchip\xc8\v1.34\bin\xc8.exe" --pass1  --chip=18F4550 -Q -G    --double=24 --float=24 --emi=wordwrite --rom=default,-0-17FF,-1806-1807,-1826-1827 --opt=+asm,-asmfile,-speed,+space,-debug --addrqual=ignore --mode=free -DKANA_MAX=KANA_X6004 -P -N255 -I"../../../../../../../../src" -I"../src" -I"../../../../../../framework" -I"../../../../../../bsp/esrille_new_keyboard" -I"../src/system_config/esrille_new_keyboard" --warn=0 --asmlist -DXPRJ_PIC18F4550_NISSE=PIC18F4550_NISSE  --summary=default,-psect,-class,+mem,-hex,-file --codeoffset=0x1800 --output=default,-inhx032 --runtime=default,+clear,+init,-keep,-no_startup,-download,+config,+clib,+plib   --output=-mcof,+elf:multilocs --stack=compiled:auto:auto:auto "--errformat=%f:%l: error: (%n) %s" "--warnformat=%f:%l: warning: (%n) %s" "--msgformat=%f:%l: advisory: (%n) %s"     -obuild/PIC18F4550_NISSE/production/_ext/1360937237/app_device_keyboard.p1 ../src/app_device_keyboard.c 
"C:\Program Files (x86)\Microchip\xc8\v1.34\bin\xc8.exe" --pass1  --chip=18F4550 -Q -G    --double=24 --float=24 --emi=wordwrite --rom=default,-0-17FF,-1806-1807,-1826-1827 --opt=+asm,-asmfile,-speed,+space,-debug --addrqual=ignore --mode=free -DKANA_MAX=KANA_X6004 -P -N255 -I"../../../../../../../../src" -I"../src" -I"../../../../../../framework" -I"../../../../../../bsp/esrille_new_keyboard" -I"../src/system_config/esrille_new_keyboard" --warn=0 --asmlist -DXPRJ_PIC18F4550_NISSE=PIC18F4550_NISSE  --summary=default,-psect,-class,+mem,-hex,-file --codeoffset=0x1800 --output=default,-inhx032 --runtime=default,+clear,+init,-keep,-no_startup,-download,+config,+clib,+plib   --output=-mcof,+elf:multilocs --stack=compiled:auto:auto:auto "--errformat=%f:%l: error: (%n) %s" "--warnformat=%f:%l: warning: (%n) %s" "--msgformat=%f:%l: advisory: (%n) %s"     -obuild/PIC18F4550_NISSE/production/_ext/770305540/system.p1 ../src/system_config/esrille_new_keyboard/system.c 
"C:\Program Files (x86)\Microchip\xc8\v1.34\bin\xc8.exe" --pass1  --chip=18F4550 -Q -G    --double=24 --float=24 --emi=wordwrite --rom=default,-0-17FF,-1806-1807,-1826-1827 --opt=+asm,-asmfile,-speed,+space,-debug --addrqual=ignore --mode=free -DKANA_MAX=KANA_X6004 -P -N255 -I"../../../../../../../../src" -I"../src" -I"../../../../../../framework" -I"../../../../../../bsp/esrille_new_keyboard" -I"../src/system_config/esrille_new_keyboard" --warn=0 --asmlist -DXPRJ_PIC18F4550_NISSE=PIC18F4550_NISSE  --summary=default,-psect,-class,+mem,-hex,-file --codeoffset=0x1800 --output=default,-inhx032 --runtime=default,+clear,+init,-keep,-no_startup,-download,+config,+clib,+plib   --output=-mcof,+elf:multilocs --stack=compiled:auto:auto:auto "--errformat=%f:%l: error: (%n) %s" "--warnformat=%f:%l: warning: (%n) %s" "--msgformat=%f:%l: advisory: (%n) %s"     -obuild/PIC18F4550_NISSE/production/_ext/1360937237/main.p1 ../src/main.c 
"C:\Program Files (x86)\Microchip\xc8\v1.34\bin\xc8.exe" --pass1  --chip=18F4550 -Q -G    --double=24 --float=24 --emi=wordwrite --rom=default,-0-17FF,-1806-1807,-1826-1827 --opt=+asm,-asmfile,-speed,+space,-debug --addrqual=ignore --mode=free -DKANA_MAX=KANA_X6004 -P -N255 -I"../../../../../../../../src" -I"../src" -I"../../../../../../framework" -I"../../../../../../bsp/esrille_new_keyboard" -I"../src/system_config/esrille_new_keyboard" --warn=0 --asmlist -DXPRJ_PIC18F4550_NISSE=PIC18F4550_NISSE  --summary=default,-psect,-class,+mem,-hex,-file --codeoffset=0x1800 --output=default,-inhx032 --runtime=default,+clear,+init,-keep,-no_startup,-download,+config,+clib,+plib   --output=-mcof,+elf:multilocs --stack=compiled:auto:auto:auto "--errformat=%f:%l: error: (%n) %s" "--warnformat=%f:%l: warning: (%n) %s" "--msgformat=%f:%l: advisory: (%n) %s"     -obuild/PIC18F4550_NISSE/production/_ext/1360937237/usb_descriptors.p1 ../src/usb_descriptors.c 
"C:\Program Files (x86)\Microchip\xc8\v1.34\bin\xc8.exe" --pass1  --chip=18F4550 -Q -G    --double=24 --float=24 --emi=wordwrite --rom=default,-0-17FF,-1806-1807,-1826-1827 --opt=+asm,-asmfile,-speed,+space,-debug --addrqual=ignore --mode=free -DKANA_MAX=KANA_X6004 -P -N255 -I"../../../../../../../../src" -I"../src" -I"../../../../../../framework" -I"../../../../../../bsp/esrille_new_keyboard" -I"../src/system_config/esrille_new_keyboard" --warn=0 --asmlist -DXPRJ_PIC18F4550_NISSE=PIC18F4550_NISSE  --summary=default,-psect,-class,+mem,-hex,-file --codeoffset=0x1800 --output=default,-inhx032 --runtime=default,+clear,+init,-keep,-no_startup,-download,+config,+clib,+plib   --output=-mcof,+elf:multilocs --stack=compiled:auto:auto:auto "--errformat=%f:%l: error: (%n) %s" "--warnformat=%f:%l: warning: (%n) %s" "--msgformat=%f:%l: advisory: (%n) %s"     -obuild/PIC18F4550_NISSE/production/_ext/978351403/leds.p1 ../../../../../../bsp/esrille_new_keyboard/leds.c 
"C:\Program Files (x86)\Microchip\xc8\v1.34\bin\xc8.exe" --pass1  --chip=18F4550 -Q -G    --double=24 --float=24 --emi=wordwrite --rom=default,-0-17FF,-1806-1807,-1826-1827 --opt=+asm,-asmfile,-speed,+space,-debug --addrqual=ignore --mode=free -DKANA_MAX=KANA_X6004 -P -N255 -I"../../../../../../../../src" -I"../src" -I"../../../../../../framework" -I"../../../../../../bsp/esrille_new_keyboard" -I"../src/system_config/esrille_new_keyboard" --warn=0 --asmlist -DXPRJ_PIC18F4550_NISSE=PIC18F4550_NISSE  --summary=default,-psect,-class,+mem,-hex,-file --codeoffset=0x1800 --output=default,-inhx032 --runtime=default,+clear,+init,-keep,-no_startup,-download,+config,+clib,+plib   --output=-mcof,+elf:multilocs --stack=compiled:auto:auto:auto "--errformat=%f:%l: error: (%n) %s" "--warnformat=%f:%l: warning: (%n) %s" "--msgformat=%f:%l: advisory: (%n) %s"     -obuild/PIC18F4550_NISSE/production/_ext/838585624/usb_device.p1 ../../../../../../framework/usb/src/usb_device.c 
"C:\Program Files (x86)\Microchip\xc8\v1.34\bin\xc8.exe" --pass1  --chip=18F4550 -Q -G    --double=24 --float=24 --emi=wordwrite --rom=default,-0-17FF,-1806-1807,-1826-1827 --opt=+asm,-asmfile,-speed,+space,-debug --addrqual=ignore --mode=free -DKANA_MAX=KANA_X6004 -P -N255 -I"../../../../../../../../src" -I"../src" -I"../../../../../../framework" -I"../../../../../../bsp/esrille_new_keyboard" -I"../src/system_config/esrille_new_keyboard" --warn=0 --asmlist -DXPRJ_PIC18F4550_NISSE=PIC18F4550_NISSE  --summary=default,-psect,-class,+mem,-hex,-file --codeoffset=0x1800 --output=default,-inhx032 --runtime=default,+clear,+init,-keep,-no_startup,-download,+config,+clib,+plib   --output=-mcof,+elf:multilocs --stack=compiled:auto:auto:auto "--errformat=%f:%l: error: (%n) %s" "--warnformat=%f:%l: warning: (%n) %s" "--msgformat=%f:%l: advisory: (%n) %s"     -obuild/PIC18F4550_NISSE/production/_ext/838585624/usb_device_hid.p1 ../../../../../../framework/usb/src/usb_device_hid.c 
"C:\Program Files (x86)\Microchip\xc8\v1.34\bin\xc8.exe" --pass1  --chip=18F4550 -Q -G    --double=24 --float=24 --emi=wordwrite --rom=default,-0-17FF,-1806-1807,-1826-1827 --opt=+asm,-asmfile,-speed,+space,-debug --addrqual=ignore --mode=free -DKANA_MAX=KANA_X6004 -P -N255 -I"../../../../../../../../src" -I"../src" -I"../../../../../../framework" -I"../../../../../../bsp/esrille_new_keyboard" -I"../src/system_config/esrille_new_keyboard" --warn=0 --asmlist -DXPRJ_PIC18F4550_NISSE=PIC18F4550_NISSE  --summary=default,-psect,-class,+mem,-hex,-file --codeoffset=0x1800 --output=default,-inhx032 --runtime=default,+clear,+init,-keep,-no_startup,-download,+config,+clib,+plib   --output=-mcof,+elf:multilocs --stack=compiled:auto:auto:auto "--errformat=%f:%l: error: (%n) %s" "--warnformat=%f:%l: warning: (%n) %s" "--msgformat=%f:%l: advisory: (%n) %s"     -obuild/PIC18F4550_NISSE/production/_ext/978351403/buttons.p1 ../../../../../../bsp/esrille_new_keyboard/buttons.c 
"C:\Program Files (x86)\Microchip\xc8\v1.34\bin\xc8.exe" --pass1  --chip=18F4550 -Q -G    --double=24 --float=24 --emi=wordwrite --rom=default,-0-17FF,-1806-1807,-1826-1827 --opt=+asm,-asmfile,-speed,+space,-debug --addrqual=ignore --mode=free -DKANA_MAX=KANA_X6004 -P -N255 -I"../../../../../../../../src" -I"../src" -I"../../../../../../framework" -I"../../../../../../bsp/esrille_new_keyboard" -I"../src/system_config/esrille_new_keyboard" --warn=0 --asmlist -DXPRJ_PIC18F4550_NISSE=PIC18F4550_NISSE  --summary=default,-psect,-class,+mem,-hex,-file --codeoffset=0x1800 --output=default,-inhx032 --runtime=default,+clear,+init,-keep,-no_startup,-download,+config,+clib,+plib   --output=-mcof,+elf:multilocs --stack=compiled:auto:auto:auto "--errformat=%f:%l: error: (%n) %s" "--warnformat=%f:%l: warning: (%n) %s" "--msgformat=%f:%l: advisory: (%n) %s"     -obuild/PIC18F4550_NISSE/production/_ext/309221532/KeyboardCommon.p1 ../../../../../../../../src/KeyboardCommon.c 
"C:\Program Files (x86)\Microchip\xc8\v1.34\bin\xc8.exe" --pass1  --chip=18F4550 -Q -G    --double=24 --float=24 --emi=wordwrite --rom=default,-0-17FF,-1806-1807,-1826-1827 --opt=+asm,-asmfile,-speed,+space,-debug --addrqual=ignore --mode=free -DKANA_MAX=KANA_X6004 -P -N255 -I"../../../../../../../../src" -I"../src" -I"../../../../../../framework" -I"../../../../../../bsp/esrille_new_keyboard" -I"../src/system_config/esrille_new_keyboard" --warn=0 --asmlist -DXPRJ_PIC18F4550_NISSE=PIC18F4550_NISSE  --summary=default,-psect,-class,+mem,-hex,-file --codeoffset=0x1800 --output=default,-inhx032 --runtime=default,+clear,+init,-keep,-no_startup,-download,+config,+clib,+plib   --output=-mcof,+elf:multilocs --stack=compiled:auto:auto:auto "--errformat=%f:%l: error: (%n) %s" "--warnformat=%f:%l: warning: (%n) %s" "--msgformat=%f:%l: advisory: (%n) %s"     -obuild/PIC18F4550_NISSE/production/_ext/309221532/KeyboardJP.p1 ../../../../../../../../src/KeyboardJP.c 
"C:\Program Files (x86)\Microchip\xc8\v1.34\bin\xc8.exe" --pass1  --chip=18F4550 -Q -G    --double=24 --float=24 --emi=wordwrite --rom=default,-0-17FF,-1806-1807,-1826-1827 --opt=+asm,-asmfile,-speed,+space,-debug --addrqual=ignore --mode=free -DKANA_MAX=KANA_X6004 -P -N255 -I"../../../../../../../../src" -I"../src" -I"../../../../../../framework" -I"../../../../../../bsp/esrille_new_keyboard" -I"../src/system_config/esrille_new_keyboard" --warn=0 --asmlist -DXPRJ_PIC18F4550_NISSE=PIC18F4550_NISSE  --summary=default,-psect,-class,+mem,-hex,-file --codeoffset=0x1800 --output=default,-inhx032 --runtime=default,+clear,+init,-keep,-no_startup,-download,+config,+clib,+plib   --output=-mcof,+elf:multilocs --stack=compiled:auto:auto:auto "--errformat=%f:%l: error: (%n) %s" "--warnformat=%f:%l: warning: (%n) %s" "--msgformat=%f:%l: advisory: (%n) %s"     -obuild/PIC18F4550_NISSE/production/_ext/309221532/KeyboardUS.p1 ../../../../../../../../src/KeyboardUS.c 
make[2]: *** [build/PIC18F4550_NISSE/production/_ext/838585624/usb_device.p1] Error 1
make[1]: *** [.build-conf] Error 2
make: *** [.build-impl] Error 2
(908) exit status = 1
nbproject/Makefile-PIC18F4550_NISSE.mk:251: recipe for target 'build/PIC18F4550_NISSE/production/_ext/838585624/usb_device.p1' failed
make[2]: Leaving directory 'C:/Users/JJ/Downloads/new-keyboard-master/new-keyboard-master/firmware/third_party/mla_v2013_12_20/apps/usb/device/hid_keyboard/firmware/MPLAB.X'
nbproject/Makefile-PIC18F4550_NISSE.mk:91: recipe for target '.build-conf' failed
make[1]: Leaving directory 'C:/Users/JJ/Downloads/new-keyboard-master/new-keyboard-master/firmware/third_party/mla_v2013_12_20/apps/usb/device/hid_keyboard/firmware/MPLAB.X'
nbproject/Makefile-impl.mk:39: recipe for target '.build-impl' failed

BUILD FAILED (exit value 2, total time: 1s)
```
Here is configuration loading error:  

```  
warning: Configuration "PIC18F4550_NISSE" builds with "XC8 v1.34", but indicates no toolchain directory.
info: Configuration "PIC18F4550_NISSE" will build with toolchain "XC8 v1.34" at "C:\Program Files (x86)\Microchip\xc8\v1.34\bin".

```

I also tried using another windows 10 computer however the build still fails. Should I try to use an older version of MPLAB X IDE?

**Comment by ShikiOkasaka** [comment]
It seems that the generated files by MPLAB X on your PC still have something wrong.
The configuration loading error should also have been resolved before using Clean and Build project.
Please use a clean source tree and regenerate MPLAB X files as suggested in the Microchip forum.
We don't see any significant issues with MPLAB X IDE v5.5 at our site.
If everything goes well, you should see the output something like below:

```
CLEAN SUCCESSFUL (total time: 18ms)
make -f nbproject/Makefile-PIC18F4550_NISSE.mk SUBPROJECTS= .build-conf
make[1]: Entering directory 'C:/Users/JJ/Downloads/new-keyboard-master/new-keyboard-master/firmware/third_party/mla_v2013_12_20/apps/usb/device/hid_keyboard/firmware/MPLAB.X'
make  -f nbproject/Makefile-PIC18F4550_NISSE.mk dist/PIC18F4550_NISSE/production/MPLAB.X.production.hex
make[2]: Entering directory 'C:/Users/JJ/Downloads/new-keyboard-master/new-keyboard-master/firmware/third_party/mla_v2013_12_20/apps/usb/device/hid_keyboard/firmware/MPLAB.X'
"C:\Program Files (x86)\Microchip\xc8\v1.34\bin\xc8.exe" --pass1  --chip=18F4550 -Q -G    --double=24 --float=24 --emi=wordwrite --rom=default,-0-17FF,-1806-1807,-1826-1827 --opt=+asm,-asmfile,-speed,+space,-debug --addrqual=ignore --mode=free -DKANA_MAX=KANA_X6004 -P -N255 -I"../../../../../../../../src" -I"../src" -I"../../../../../../framework" -I"../../../../../../bsp/esrille_new_keyboard" -I"../src/system_config/esrille_new_keyboard" --warn=0 --asmlist -DXPRJ_PIC18F4550_NISSE=PIC18F4550_NISSE  --summary=default,-psect,-class,+mem,-hex,-file --codeoffset=0x1800 --output=default,-inhx032 --runtime=default,+clear,+init,-keep,-no_startup,-download,+config,+clib,+plib   --output=-mcof,+elf:multilocs --stack=compiled:auto:auto:auto "--errformat=%f:%l: error: (%n) %s" "--warnformat=%f:%l: warning: (%n) %s" "--msgformat=%f:%l: advisory: (%n) %s"     -obuild/PIC18F4550_NISSE/production/_ext/1360937237/app_led_usb_status.p1 ../src/app_led_usb_status.c 
"C:\Program Files (x86)\Microchip\xc8\v1.34\bin\xc8.exe" --pass1  --chip=18F4550 -Q -G    --double=24 --float=24 --emi=wordwrite --rom=default,-0-17FF,-1806-1807,-1826-1827 --opt=+asm,-asmfile,-speed,+space,-debug --addrqual=ignore --mode=free -DKANA_MAX=KANA_X6004 -P -N255 -I"../../../../../../../../src" -I"../src" -I"../../../../../../framework" -I"../../../../../../bsp/esrille_new_keyboard" -I"../src/system_config/esrille_new_keyboard" --warn=0 --asmlist -DXPRJ_PIC18F4550_NISSE=PIC18F4550_NISSE  --summary=default,-psect,-class,+mem,-hex,-file --codeoffset=0x1800 --output=default,-inhx032 --runtime=default,+clear,+init,-keep,-no_startup,-download,+config,+clib,+plib   --output=-mcof,+elf:multilocs --stack=compiled:auto:auto:auto "--errformat=%f:%l: error: (%n) %s" "--warnformat=%f:%l: warning: (%n) %s" "--msgformat=%f:%l: advisory: (%n) %s"     -obuild/PIC18F4550_NISSE/production/_ext/1360937237/app_device_keyboard.p1 ../src/app_device_keyboard.c 
"C:\Program Files (x86)\Microchip\xc8\v1.34\bin\xc8.exe" --pass1  --chip=18F4550 -Q -G    --double=24 --float=24 --emi=wordwrite --rom=default,-0-17FF,-1806-1807,-1826-1827 --opt=+asm,-asmfile,-speed,+space,-debug --addrqual=ignore --mode=free -DKANA_MAX=KANA_X6004 -P -N255 -I"../../../../../../../../src" -I"../src" -I"../../../../../../framework" -I"../../../../../../bsp/esrille_new_keyboard" -I"../src/system_config/esrille_new_keyboard" --warn=0 --asmlist -DXPRJ_PIC18F4550_NISSE=PIC18F4550_NISSE  --summary=default,-psect,-class,+mem,-hex,-file --codeoffset=0x1800 --output=default,-inhx032 --runtime=default,+clear,+init,-keep,-no_startup,-download,+config,+clib,+plib   --output=-mcof,+elf:multilocs --stack=compiled:auto:auto:auto "--errformat=%f:%l: error: (%n) %s" "--warnformat=%f:%l: warning: (%n) %s" "--msgformat=%f:%l: advisory: (%n) %s"     -obuild/PIC18F4550_NISSE/production/_ext/1360937237/main.p1 ../src/main.c 
"C:\Program Files (x86)\Microchip\xc8\v1.34\bin\xc8.exe" --pass1  --chip=18F4550 -Q -G    --double=24 --float=24 --emi=wordwrite --rom=default,-0-17FF,-1806-1807,-1826-1827 --opt=+asm,-asmfile,-speed,+space,-debug --addrqual=ignore --mode=free -DKANA_MAX=KANA_X6004 -P -N255 -I"../../../../../../../../src" -I"../src" -I"../../../../../../framework" -I"../../../../../../bsp/esrille_new_keyboard" -I"../src/system_config/esrille_new_keyboard" --warn=0 --asmlist -DXPRJ_PIC18F4550_NISSE=PIC18F4550_NISSE  --summary=default,-psect,-class,+mem,-hex,-file --codeoffset=0x1800 --output=default,-inhx032 --runtime=default,+clear,+init,-keep,-no_startup,-download,+config,+clib,+plib   --output=-mcof,+elf:multilocs --stack=compiled:auto:auto:auto "--errformat=%f:%l: error: (%n) %s" "--warnformat=%f:%l: warning: (%n) %s" "--msgformat=%f:%l: advisory: (%n) %s"     -obuild/PIC18F4550_NISSE/production/_ext/1360937237/usb_descriptors.p1 ../src/usb_descriptors.c 
"C:\Program Files (x86)\Microchip\xc8\v1.34\bin\xc8.exe" --pass1  --chip=18F4550 -Q -G    --double=24 --float=24 --emi=wordwrite --rom=default,-0-17FF,-1806-1807,-1826-1827 --opt=+asm,-asmfile,-speed,+space,-debug --addrqual=ignore --mode=free -DKANA_MAX=KANA_X6004 -P -N255 -I"../../../../../../../../src" -I"../src" -I"../../../../../../framework" -I"../../../../../../bsp/esrille_new_keyboard" -I"../src/system_config/esrille_new_keyboard" --warn=0 --asmlist -DXPRJ_PIC18F4550_NISSE=PIC18F4550_NISSE  --summary=default,-psect,-class,+mem,-hex,-file --codeoffset=0x1800 --output=default,-inhx032 --runtime=default,+clear,+init,-keep,-no_startup,-download,+config,+clib,+plib   --output=-mcof,+elf:multilocs --stack=compiled:auto:auto:auto "--errformat=%f:%l: error: (%n) %s" "--warnformat=%f:%l: warning: (%n) %s" "--msgformat=%f:%l: advisory: (%n) %s"     -obuild/PIC18F4550_NISSE/production/_ext/838585624/usb_device_hid.p1 ../../../../../../framework/usb/src/usb_device_hid.c 
"C:\Program Files (x86)\Microchip\xc8\v1.34\bin\xc8.exe" --pass1  --chip=18F4550 -Q -G    --double=24 --float=24 --emi=wordwrite --rom=default,-0-17FF,-1806-1807,-1826-1827 --opt=+asm,-asmfile,-speed,+space,-debug --addrqual=ignore --mode=free -DKANA_MAX=KANA_X6004 -P -N255 -I"../../../../../../../../src" -I"../src" -I"../../../../../../framework" -I"../../../../../../bsp/esrille_new_keyboard" -I"../src/system_config/esrille_new_keyboard" --warn=0 --asmlist -DXPRJ_PIC18F4550_NISSE=PIC18F4550_NISSE  --summary=default,-psect,-class,+mem,-hex,-file --codeoffset=0x1800 --output=default,-inhx032 --runtime=default,+clear,+init,-keep,-no_startup,-download,+config,+clib,+plib   --output=-mcof,+elf:multilocs --stack=compiled:auto:auto:auto "--errformat=%f:%l: error: (%n) %s" "--warnformat=%f:%l: warning: (%n) %s" "--msgformat=%f:%l: advisory: (%n) %s"     -obuild/PIC18F4550_NISSE/production/_ext/838585624/usb_device.p1 ../../../../../../framework/usb/src/usb_device.c 
"C:\Program Files (x86)\Microchip\xc8\v1.34\bin\xc8.exe" --pass1  --chip=18F4550 -Q -G    --double=24 --float=24 --emi=wordwrite --rom=default,-0-17FF,-1806-1807,-1826-1827 --opt=+asm,-asmfile,-speed,+space,-debug --addrqual=ignore --mode=free -DKANA_MAX=KANA_X6004 -P -N255 -I"../../../../../../../../src" -I"../src" -I"../../../../../../framework" -I"../../../../../../bsp/esrille_new_keyboard" -I"../src/system_config/esrille_new_keyboard" --warn=0 --asmlist -DXPRJ_PIC18F4550_NISSE=PIC18F4550_NISSE  --summary=default,-psect,-class,+mem,-hex,-file --codeoffset=0x1800 --output=default,-inhx032 --runtime=default,+clear,+init,-keep,-no_startup,-download,+config,+clib,+plib   --output=-mcof,+elf:multilocs --stack=compiled:auto:auto:auto "--errformat=%f:%l: error: (%n) %s" "--warnformat=%f:%l: warning: (%n) %s" "--msgformat=%f:%l: advisory: (%n) %s"     -obuild/PIC18F4550_NISSE/production/_ext/309221532/KeyboardCommon.p1 ../../../../../../../../src/KeyboardCommon.c 
"C:\Program Files (x86)\Microchip\xc8\v1.34\bin\xc8.exe" --pass1  --chip=18F4550 -Q -G    --double=24 --float=24 --emi=wordwrite --rom=default,-0-17FF,-1806-1807,-1826-1827 --opt=+asm,-asmfile,-speed,+space,-debug --addrqual=ignore --mode=free -DKANA_MAX=KANA_X6004 -P -N255 -I"../../../../../../../../src" -I"../src" -I"../../../../../../framework" -I"../../../../../../bsp/esrille_new_keyboard" -I"../src/system_config/esrille_new_keyboard" --warn=0 --asmlist -DXPRJ_PIC18F4550_NISSE=PIC18F4550_NISSE  --summary=default,-psect,-class,+mem,-hex,-file --codeoffset=0x1800 --output=default,-inhx032 --runtime=default,+clear,+init,-keep,-no_startup,-download,+config,+clib,+plib   --output=-mcof,+elf:multilocs --stack=compiled:auto:auto:auto "--errformat=%f:%l: error: (%n) %s" "--warnformat=%f:%l: warning: (%n) %s" "--msgformat=%f:%l: advisory: (%n) %s"     -obuild/PIC18F4550_NISSE/production/_ext/770305540/system.p1 ../src/system_config/esrille_new_keyboard/system.c 
"C:\Program Files (x86)\Microchip\xc8\v1.34\bin\xc8.exe" --pass1  --chip=18F4550 -Q -G    --double=24 --float=24 --emi=wordwrite --rom=default,-0-17FF,-1806-1807,-1826-1827 --opt=+asm,-asmfile,-speed,+space,-debug --addrqual=ignore --mode=free -DKANA_MAX=KANA_X6004 -P -N255 -I"../../../../../../../../src" -I"../src" -I"../../../../../../framework" -I"../../../../../../bsp/esrille_new_keyboard" -I"../src/system_config/esrille_new_keyboard" --warn=0 --asmlist -DXPRJ_PIC18F4550_NISSE=PIC18F4550_NISSE  --summary=default,-psect,-class,+mem,-hex,-file --codeoffset=0x1800 --output=default,-inhx032 --runtime=default,+clear,+init,-keep,-no_startup,-download,+config,+clib,+plib   --output=-mcof,+elf:multilocs --stack=compiled:auto:auto:auto "--errformat=%f:%l: error: (%n) %s" "--warnformat=%f:%l: warning: (%n) %s" "--msgformat=%f:%l: advisory: (%n) %s"     -obuild/PIC18F4550_NISSE/production/_ext/978351403/leds.p1 ../../../../../../bsp/esrille_new_keyboard/leds.c 
"C:\Program Files (x86)\Microchip\xc8\v1.34\bin\xc8.exe" --pass1  --chip=18F4550 -Q -G    --double=24 --float=24 --emi=wordwrite --rom=default,-0-17FF,-1806-1807,-1826-1827 --opt=+asm,-asmfile,-speed,+space,-debug --addrqual=ignore --mode=free -DKANA_MAX=KANA_X6004 -P -N255 -I"../../../../../../../../src" -I"../src" -I"../../../../../../framework" -I"../../../../../../bsp/esrille_new_keyboard" -I"../src/system_config/esrille_new_keyboard" --warn=0 --asmlist -DXPRJ_PIC18F4550_NISSE=PIC18F4550_NISSE  --summary=default,-psect,-class,+mem,-hex,-file --codeoffset=0x1800 --output=default,-inhx032 --runtime=default,+clear,+init,-keep,-no_startup,-download,+config,+clib,+plib   --output=-mcof,+elf:multilocs --stack=compiled:auto:auto:auto "--errformat=%f:%l: error: (%n) %s" "--warnformat=%f:%l: warning: (%n) %s" "--msgformat=%f:%l: advisory: (%n) %s"     -obuild/PIC18F4550_NISSE/production/_ext/309221532/KeyboardJP.p1 ../../../../../../../../src/KeyboardJP.c 
"C:\Program Files (x86)\Microchip\xc8\v1.34\bin\xc8.exe" --pass1  --chip=18F4550 -Q -G    --double=24 --float=24 --emi=wordwrite --rom=default,-0-17FF,-1806-1807,-1826-1827 --opt=+asm,-asmfile,-speed,+space,-debug --addrqual=ignore --mode=free -DKANA_MAX=KANA_X6004 -P -N255 -I"../../../../../../../../src" -I"../src" -I"../../../../../../framework" -I"../../../../../../bsp/esrille_new_keyboard" -I"../src/system_config/esrille_new_keyboard" --warn=0 --asmlist -DXPRJ_PIC18F4550_NISSE=PIC18F4550_NISSE  --summary=default,-psect,-class,+mem,-hex,-file --codeoffset=0x1800 --output=default,-inhx032 --runtime=default,+clear,+init,-keep,-no_startup,-download,+config,+clib,+plib   --output=-mcof,+elf:multilocs --stack=compiled:auto:auto:auto "--errformat=%f:%l: error: (%n) %s" "--warnformat=%f:%l: warning: (%n) %s" "--msgformat=%f:%l: advisory: (%n) %s"     -obuild/PIC18F4550_NISSE/production/_ext/309221532/KeyboardUS.p1 ../../../../../../../../src/KeyboardUS.c 
"C:\Program Files (x86)\Microchip\xc8\v1.34\bin\xc8.exe" --pass1  --chip=18F4550 -Q -G    --double=24 --float=24 --emi=wordwrite --rom=default,-0-17FF,-1806-1807,-1826-1827 --opt=+asm,-asmfile,-speed,+space,-debug --addrqual=ignore --mode=free -DKANA_MAX=KANA_X6004 -P -N255 -I"../../../../../../../../src" -I"../src" -I"../../../../../../framework" -I"../../../../../../bsp/esrille_new_keyboard" -I"../src/system_config/esrille_new_keyboard" --warn=0 --asmlist -DXPRJ_PIC18F4550_NISSE=PIC18F4550_NISSE  --summary=default,-psect,-class,+mem,-hex,-file --codeoffset=0x1800 --output=default,-inhx032 --runtime=default,+clear,+init,-keep,-no_startup,-download,+config,+clib,+plib   --output=-mcof,+elf:multilocs --stack=compiled:auto:auto:auto "--errformat=%f:%l: error: (%n) %s" "--warnformat=%f:%l: warning: (%n) %s" "--msgformat=%f:%l: advisory: (%n) %s"     -obuild/PIC18F4550_NISSE/production/_ext/978351403/buttons.p1 ../../../../../../bsp/esrille_new_keyboard/buttons.c 
"C:\Program Files (x86)\Microchip\xc8\v1.34\bin\xc8.exe"  --chip=18F4550 -G -mdist/PIC18F4550_NISSE/production/MPLAB.X.production.map  -DXPRJ_PIC18F4550_NISSE=PIC18F4550_NISSE    --double=24 --float=24 --emi=wordwrite --rom=default,-0-17FF,-1806-1807,-1826-1827 --opt=+asm,-asmfile,-speed,+space,-debug --addrqual=ignore --mode=free -DKANA_MAX=KANA_X6004 -P -N255 -I"../../../../../../../../src" -I"../src" -I"../../../../../../framework" -I"../../../../../../bsp/esrille_new_keyboard" -I"../src/system_config/esrille_new_keyboard" --warn=0 --asmlist --summary=default,-psect,-class,+mem,-hex,-file --codeoffset=0x1800 --output=default,-inhx032 --runtime=default,+clear,+init,-keep,-no_startup,-download,+config,+clib,+plib --output=-mcof,+elf:multilocs --stack=compiled:auto:auto:auto "--errformat=%f:%l: error: (%n) %s" "--warnformat=%f:%l: warning: (%n) %s" "--msgformat=%f:%l: advisory: (%n) %s"      --memorysummary dist/PIC18F4550_NISSE/production/memoryfile.xml -odist/PIC18F4550_NISSE/production/MPLAB.X.production.elf  build/PIC18F4550_NISSE/production/_ext/770305540/system.p1 build/PIC18F4550_NISSE/production/_ext/1360937237/app_device_keyboard.p1 build/PIC18F4550_NISSE/production/_ext/1360937237/app_led_usb_status.p1 build/PIC18F4550_NISSE/production/_ext/1360937237/main.p1 build/PIC18F4550_NISSE/production/_ext/1360937237/usb_descriptors.p1 build/PIC18F4550_NISSE/production/_ext/978351403/buttons.p1 build/PIC18F4550_NISSE/production/_ext/978351403/leds.p1 build/PIC18F4550_NISSE/production/_ext/838585624/usb_device.p1 build/PIC18F4550_NISSE/production/_ext/838585624/usb_device_hid.p1 build/PIC18F4550_NISSE/production/_ext/309221532/KeyboardCommon.p1 build/PIC18F4550_NISSE/production/_ext/309221532/KeyboardJP.p1 build/PIC18F4550_NISSE/production/_ext/309221532/KeyboardUS.p1     
Microchip MPLAB XC8 C Compiler (Free Mode) V1.34
Build date: Feb 16 2015
Part Support Version: 1.34
Copyright (C) 2015 Microchip Technology Inc.
License type: Node Configuration

:: advisory: (1233) Employing 18F4550 errata work-arounds:
:: advisory: (1234)  * Corrupted fast interrupt shadow registers
:: warning: (1273) Omniscient Code Generation not available in Free mode
../../../../../../../../src/KeyboardCommon.c:756: warning: (765) degenerate unsigned comparison

Memory Summary:
    Program space        used  5A88h ( 23176) of  6800h bytes   ( 87.0%)
    Data space           used   316h (   790) of   800h bytes   ( 38.6%)
    Configuration bits   used     7h (     7) of     7h words   (100.0%)
    EEPROM space         used    10h (    16) of   100h bytes   (  6.2%)
    ID Location space    used     8h (     8) of     8h bytes   (100.0%)
    Data stack space     used     0h (     0) of   2F7h bytes   (  0.0%)

Running this compiler in PRO mode, with Omniscient Code Generation enabled,
often produces code which is 60% smaller and at least 400% faster than in
Free mode. The MPLAB XC8 PRO compiler output for this code could be
13905 bytes smaller and run 4 times faster.
See http://www.microchip.com/MPLABXCcompilers for more information.

make[2]: Leaving directory 'C:/Users/JJ/Downloads/new-keyboard-master/new-keyboard-master/firmware/third_party/mla_v2013_12_20/apps/usb/device/hid_keyboard/firmware/MPLAB.X'
make[1]: Leaving directory 'C:/Users/JJ/Downloads/new-keyboard-master/new-keyboard-master/firmware/third_party/mla_v2013_12_20/apps/usb/device/hid_keyboard/firmware/MPLAB.X'

BUILD SUCCESSFUL (total time: 7s)
Loading code from C:/Users/JJ/Downloads/new-keyboard-master/new-keyboard-master/firmware/third_party/mla_v2013_12_20/apps/usb/device/hid_keyboard/firmware/MPLAB.X/dist/PIC18F4550_NISSE/production/MPLAB.X.production.hex...
Program loaded with pack,PIC18Fxxxx_DFP,1.1.19,Microchip
Loading completed
```

**Comment by wagyuA5** [comment]
Hello I tried every other project configuration, and they were successfully built! It seems that the problem only seems to be with the PIC18F4550_NISSE. Can you confirm this? Thanks

**Comment by ShikiOkasaka** [comment]
Good to hear you have made some progress.
We do not see any issue with the current master tree with MPLAB X IDE v5.5.
With the fresh installation of MPLAB X IDE v5.5, the following steps work fine at our site.

1. Download ZIP from https://github.com/esrille/new-keyboard.
1. Extract the files.
1. Open C:\Users\[YOUR NAME]\Downloads\new-keyboard-master\new-keyboard-master\firmware\third_party\mla_v2013_12_20\apps\usb\device\hid_keyboard\firmware\MPLAB.X
1. Build the project.

It sounds like that several MPLAB X configuration files on your PC have been corrupted.
Please follow the instructions described in the following page, and try again:

https://microchipdeveloper.com/mplabx:persistence-data

You might have to do the same with the Cache directory shown in the Help > About dialog box of the MPLAB X IDE v5.5.

**Comment by wagyuA5** [comment]
So I deleted the cache and persistence data and sadly only the PIC18F4550_NISSE configuration still does not work. Is it possible that I can flash my board with the PIC18F4550_NISSE_TSAP configuration even if it does not have the touchpad?

**Comment by ShikiOkasaka** [comment]
You can duplicate the PIC18F4550_NISSE configuration using the [Manage Configurations...] button in the Project Properties dialog.
Please test the duplicated configuration and see if it works.
If it works, simply remove the old broken PIC18F4550_NISSE configuration.
You can also duplicate the PIC18F4550_NISSE_TSAP configuration and adjust settings to match PIC18F4550_NISSE configuration.
If you have time, reinstalling MPLAB X IDE would be another option; please note that MPLAB X IDE v5.50 runs fine anyway on Ubuntu, which is our default development environment.

**Comment by wagyuA5** [comment]
Good news! I have successfully flashed my board by using PIC18F4550_NISSE_TSAP configuration. 

A weird thing is that duplicating PIC18F4550_NISSE_TSAP breaks it and the duplicated PIC18F4550_NISSE remains unable to build. The error seems to be concerning about makefile for all 3 configurations:

```
nbproject/Makefile-Copy_of_PIC18F4550_NISSE_TSAP.mk:275: recipe for target 'build/Copy_of_PIC18F4550_NISSE_TSAP/production/_ext/838585624/usb_device.p1' failed
make[2]: Leaving directory 'C:/Users/JJ/Downloads/new-keyboard-master/new-keyboard-master/firmware/third_party/mla_v2013_12_20/apps/usb/device/hid_keyboard/firmware/MPLAB.X'
nbproject/Makefile-Copy_of_PIC18F4550_NISSE_TSAP.mk:91: recipe for target '.build-conf' failed
make[1]: Leaving directory 'C:/Users/JJ/Downloads/new-keyboard-master/new-keyboard-master/firmware/third_party/mla_v2013_12_20/apps/usb/device/hid_keyboard/firmware/MPLAB.X'
nbproject/Makefile-impl.mk:39: recipe for target '.build-impl' failed
make[2]: *** [build/Copy_of_PIC18F4550_NISSE_TSAP/production/_ext/838585624/usb_device.p1] Error 1
make[1]: *** [.build-conf] Error 2
make: *** [.build-impl] Error 2

BUILD FAILED (exit value 2, total time: 1s)
```

 All other project configurations can be duplicated and be built correctly.

Thanks for being responsive and helping me!
